# Builds icons.css + a Font Awesome subset containing ONLY the icons the site uses.
#
# The full Font Awesome CDN stylesheet (100 KB CSS + ~260 KB of fonts, on a
# third-party origin) was render-blocking for ~14 icons. This keeps the exact
# same markup (<i class="fas fa-check">) and glyphs, but ships ~5 KB instead.
#
# Using a NEW icon? Add its name to ICONS below, then run:
#
#   py -m pip install fonttools brotli      (once)
#   py tools/build-icons.py
#
# The script downloads Font Awesome 6.4.0 from cdnjs, so it needs internet.

import hashlib, io, os, re, urllib.request
from fontTools import subset
from fontTools.ttLib import TTFont

FA_VERSION = '6.4.0'
ICONS = {
    'solid': ['chevron-right', 'check', 'check-circle', 'envelope', 'phone', 'map-marker-alt',
              'comment-dots', 'link', 'image', 'building', 'user'],
    'brands': ['facebook-f', 'instagram', 'tiktok'],
}

ROOT = os.path.join(os.path.dirname(__file__), '..')
FONT_DIR = os.path.join(ROOT, 'assets', 'fonts')
CDN = f'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/{FA_VERSION}'
FILES = {'solid': ('fa-solid-900', 'Font Awesome 6 Free', 900), 'brands': ('fa-brands-400', 'Font Awesome 6 Brands', 400)}


def fetch(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


css = fetch(f'{CDN}/css/all.min.css').decode('utf-8')
out = [
    f'/* Font Awesome Free {FA_VERSION} subset — generated by tools/build-icons.py, do not edit by hand.',
    ' * License: https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT)',
    ' * Included icons: ' + ', '.join(sorted(ICONS['solid'] + ICONS['brands'])) + ' */',
    '.fa{font-family:var(--fa-style-family,"Font Awesome 6 Free");font-weight:var(--fa-style,900)}',
    '.fa,.fa-brands,.fa-classic,.fa-regular,.fa-sharp,.fa-solid,.fab,.far,.fas{-moz-osx-font-smoothing:grayscale;'
    '-webkit-font-smoothing:antialiased;display:var(--fa-display,inline-block);font-style:normal;font-variant:normal;'
    'line-height:1;text-rendering:auto}',
    '.fa-classic,.fa-regular,.fa-solid,.far,.fas{font-family:"Font Awesome 6 Free"}',
    '.fa-brands,.fab{font-family:"Font Awesome 6 Brands"}',
    '.fa-brands,.fab{font-weight:400}',
    '.fa-solid,.fas{font-weight:900}',
]

os.makedirs(FONT_DIR, exist_ok=True)
for style, names in ICONS.items():
    codepoints = []
    for name in names:
        # e.g. .fa-check-circle:before,.fa-circle-check:before{content:"\f058"}
        m = re.search(r'((?:\.[\w-]+:before,)*\.fa-' + re.escape(name) + r':before(?:,\.[\w-]+:before)*)\{content:"\\([0-9a-f]+)"\}', css)
        if not m:
            raise SystemExit(f'icon not found in Font Awesome {FA_VERSION}: {name}')
        out.append(f'{m.group(1)}{{content:"\\{m.group(2)}"}}')
        codepoints.append(int(m.group(2), 16))

    base, family, weight = FILES[style]
    font = TTFont(io.BytesIO(fetch(f'{CDN}/webfonts/{base}.woff2')))
    opts = subset.Options()
    opts.flavor = 'woff2'
    opts.layout_features = []
    opts.name_IDs = ['*']
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=codepoints)
    sub.subset(font)
    buf = io.BytesIO()
    font.flavor = 'woff2'
    font.save(buf)
    data = buf.getvalue()
    filename = f'{base}.{hashlib.sha1(data).hexdigest()[:8]}.woff2'
    for old in os.listdir(FONT_DIR):
        if old.startswith(base + '.') and old != filename:
            os.remove(os.path.join(FONT_DIR, old))
    with open(os.path.join(FONT_DIR, filename), 'wb') as f:
        f.write(data)
    out.append(f'@font-face{{font-family:"{family}";font-style:normal;font-weight:{weight};font-display:block;'
               f'src:url(assets/fonts/{filename}) format("woff2")}}')
    print(f'{filename}: {len(names)} icons, {len(data)} bytes')

with open(os.path.join(ROOT, 'icons.css'), 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(out) + '\n')
print('wrote icons.css')

# Point the <link rel="preload"> tags at the new (hashed) font files.
for html_file in ['index.html', 'terms.html']:
    path = os.path.join(ROOT, html_file)
    with open(path, encoding='utf-8', newline='') as f:
        html = f.read()
    for base, _, _ in FILES.values():
        current = next(n for n in os.listdir(FONT_DIR) if n.startswith(base + '.'))
        html = re.sub(rf'assets/fonts/{base}\.[0-9a-f]{{8}}\.woff2', f'assets/fonts/{current}', html)
    with open(path, 'w', encoding='utf-8', newline='') as f:
        f.write(html)
print('updated preload links in index.html, terms.html')
